# Generated by Django 5.2 on 2025-06-16 15:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentRozetkaModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
            options={
                'db_table': 'rozetka_app_departmentrozetkamodels',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductRoz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(blank=True, max_length=250, null=True)),
                ('category', models.CharField(blank=True, max_length=250, null=True)),
                ('name', models.CharField(max_length=500)),
                ('price', models.CharField(blank=True, max_length=50, null=True)),
                ('price_old', models.CharField(blank=True, max_length=50, null=True)),
                ('discount', models.PositiveIntegerField(blank=True, null=True)),
                ('bonus', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('status', models.CharField(default='New', max_length=25)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('link', models.CharField(max_length=250, unique=True)),
            ],
            options={
                'db_table': 'rozetka_app_productroz',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PersonModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram', models.CharField(max_length=20, unique=True, verbose_name='Telegram Username')),
                ('chat_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telegram Chat ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='person', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'People',
                'ordering': ['user__username'],
            },
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='image/')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='icons/')),
                ('product_name', models.CharField(max_length=400, verbose_name='Product Name')),
                ('link', models.URLField(blank=True, max_length=400, null=True, verbose_name='Product link')),
                ('users', models.ManyToManyField(blank=True, related_name='products', to=settings.AUTH_USER_MODEL, verbose_name='Users who added the product')),
            ],
            options={
                'verbose_name': 'Product Price',
                'verbose_name_plural': 'Product Prices',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='PriceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Price')),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Old price')),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Discount')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date Added')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='prices_app.personmodel', verbose_name='Who added the price')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='prices_app.productmodel', verbose_name='Product')),
            ],
        ),
    ]
