# Generated by Django 5.2 on 2025-07-07 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prices_app', '0002_alter_personmodel_telegram'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DepartmentRozetkaModels',
        ),
        migrations.DeleteModel(
            name='ProductRoz',
        ),
    ]
